#!/bin/bash          

# SETUP (uncomment the country you want to run!)
# CODE="CH"
# CODE="AT"
# CODE="DE"
# CODE="US"
# CODE="IT"
# CODE="GB"
# CODE="BR"
# CODE="CN"
# CODE="FR"
# CODE="CA"
# CODE="RU"
# CODE="IN"
# CODE="JP"
# CODE="PT"
# CODE="AU"
# CODE="BE"
# CODE="AR"
# CODE="TR"
# CODE="RS"
# CODE="BG"
# CODE="MK"
# CODE="NL"
# CODE="PL"
# CODE="DK"
# CODE="SE"
# CODE="NO"
# CODE="FI"
# CODE="HU"
# CODE="TW"
# CODE="AT"
# CODE="SG"
CODE="IR"

mkdir -p ./${CODE}

# Inhabited and Filtered
curl --data "$(sed s/LOCATION/${CODE}/g ./overpassScripts/scriptInhabitedFiltered.overpassql)" "http://overpass-api.de/api/interpreter" | sed s/\"//g | awk -F# 'BEGIN {print "["} NR==1 {print "[\""$1"\","$2","$3"]"} NR>1 {print ",[\""$1"\","$2","$3"]"} END { print "]"}' > ./${CODE}/dataInhabFiltered${CODE}.json

# Inhabited (unfiltered)
curl --data "$(sed s/LOCATION/${CODE}/g ./overpassScripts/scriptInhabited.overpassql)" "http://overpass-api.de/api/interpreter" | sed s/\"//g | awk -F# 'BEGIN {print "["} NR==1 {print "[\""$1"\","$2","$3"]"} NR>1 {print ",[\""$1"\","$2","$3"]"} END { print "]"}' > ./${CODE}/dataInhab${CODE}.json

# All places :)
curl --data "$(sed s/LOCATION/${CODE}/g ./overpassScripts/scriptAll.overpassql)" "http://overpass-api.de/api/interpreter" | sed s/\"//g | awk -F# 'BEGIN {print "["} NR==1 {print "[\""$1"\","$2","$3"]"} NR>1 {print ",[\""$1"\","$2","$3"]"} END { print "]"}' > ./${CODE}/dataAll${CODE}.json
