#!/bin/bash          

# SETUP
CODE="CH"
ID=3600051701
mkdir ./${CODE}

# Inhabited and Filtered
curl --data "$(sed s/LOCATION/3600051701/g ./overpassScripts/scriptInhabitedFiltered)" "http://overpass-api.de/api/interpreter" | awk -F# 'BEGIN {print "["} {print "[\""$1"\","$2","$3"],"} END { print "]"}' > ./${CODE}/dataInhabFiltered${CODE}.json

# Inhabited (unfiltered)
curl --data "$(sed s/LOCATION/3600051701/g ./overpassScripts/scriptInhabited)" "http://overpass-api.de/api/interpreter" | awk -F# 'BEGIN {print "["} {print "[\""$1"\","$2","$3"],"} END { print "]"}' > ./${CODE}/dataInhab${CODE}.json

# All places :)
curl --data "$(sed s/LOCATION/3600051701/g ./overpassScripts/scriptAll)" "http://overpass-api.de/api/interpreter" | awk -F# 'BEGIN {print "["} {print "[\""$1"\","$2","$3"],"} END { print "]"}' > ./${CODE}/dataAll${CODE}.json
